from data_structurer import CompanyData

class ReportGenerator:
    def generate_report(self, data: CompanyData) -> str:
        """
        Generates a Markdown report from the structured CompanyData.
        """
        print("Generating report...")
        
        report = f"""# {data.company_name} - Research Report

## I. Executive Summary
**Overview**: {data.mission} {data.history[:100]}...

**Key Insight**: [Generated by AI Analysis] The company is positioned as a leader in...

**Pitch Opportunity**: [Generated by AI Analysis] Leverage their recent expansion to...

## II. Foundational Analysis
- **Mission**: {data.mission}
- **Vision**: {data.vision}
- **History**: {data.history}

## III. Product & Service Deep Dive
| Name | Description | Target Customer | Core Offering |
|------|-------------|-----------------|---------------|
"""
        for p in data.products:
            report += f"| {p.name} | {p.description} | {p.target_customer} | {'Yes' if p.is_core_offering else 'No'} |\n"

        report += "\n**Core Business Areas**:\n"
        for area in data.core_business_areas:
            report += f"- {area}\n"

        report += """
## IV. Leadership & Strategy
| Name | Title | Location | LinkedIn |
|------|-------|----------|----------|
"""
        for exec in data.leadership:
            report += f"| {exec.name} | {exec.title} | {exec.location} | [Profile]({exec.linkedin_url}) |\n"

        report += f"""
**Recent Activity**:
{chr(10).join(['- ' + news for news in data.recent_news])}

## V. Competitive & Market Analysis
**SWOT Analysis**:
- **Strengths**: [Generated by AI] Strong brand recognition...
- **Weaknesses**: [Generated by AI] High operational costs...
- **Opportunities**: [Generated by AI] Emerging markets...
- **Threats**: [Generated by AI] Intense competition...

**Customer Sentiment**: {data.reviews_summary}

## VI. Pitch Opportunity Analysis
**Problem/Gap Identification**:
1. Gap 1...
2. Gap 2...

**Strategic Hook**: ...

**Recommended Next Steps**:
- Step 1...
- Step 2...
"""
        return report

    def save_report(self, report_content: str, filename: str):
        with open(filename, "w", encoding="utf-8") as f:
            f.write(report_content)
        print(f"Report saved to {filename}")
